services:
  next-app:
    container_name: next-app
    build:
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
#     networks:
#       - puc-verifica-ticket-network

# networks:
#   puc-verifica-ticket-network:
#     name: puc-verifica-ticket
#     external: true
